# Generated by Django 5.1.15 on 2026-08-27 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='Abuja', max_length=100)),
                ('state', models.CharField(default='FCT', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('banner_url', models.URLField(blank=True, default='')),
                ('latitude', models.FloatField(default=9.0765)),
                ('longitude', models.FloatField(default=7.3986)),
                ('is_open', models.BooleanField(default=True)),
                ('prep_time_minutes', models.IntegerField(default=25)),
                ('rating', models.FloatField(default=4.5)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
            },
        ),
    ]
