# Generated by Django 5.1.15 on 2026-08-27 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car')], default='motorcycle', max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('driver_license_number', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('current_latitude', models.FloatField(default=9.0765)),
                ('current_longitude', models.FloatField(default=7.3986)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'rider'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
